"""initial

Revision ID: 0d12ca28f8d8
Revises: 
Create Date: 2025-02-17 22:52:46.483891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d12ca28f8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('millage', sa.String(), nullable=False),
    sa.Column('engine_size', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('seat_material', sa.String(), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('drive', sa.String(), nullable=False),
    sa.Column('millage', sa.String(), nullable=False),
    sa.Column('engine_size', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('bikes')
    # ### end Alembic commands ###
