"""introduced a description column

Revision ID: 56e41a378a4b
Revises: 0d12ca28f8d8
Create Date: 2025-02-17 23:05:17.575389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e41a378a4b'
down_revision = '0d12ca28f8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
